openapi: 3.0.0
info:
  title: Habit Tracker API
  version: 1.0.0
  description: API for tracking habits and their completion status.

servers:
  - url: http://localhost:8000

paths:
  api/auth/register:
    post:
      summary: Register a new user
      tags: Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request
  
  api/auth/login:
    post:
      summary: Login a user
      tags: Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Unauthorized